---
run:
  go: "1.21"
linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
    - forbidigo
    - tagliatelle

linters-settings:
  tagliatelle:
    case:
      use-field-name: false
      rules:
        yaml: snake
        json: snake
