---
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
nfpms:
  - maintainer: staticdev <staticdev-support@protonmail.com>
    license: "MIT"
    description: Cleanup your phone contacts to prevent apps for having access to all details of your contacts.
    formats:
    - deb
    - rpm
archives:
  - format: zip
    replacements:
      darwin: Mac
      linux: Linux
      windows: Windows
      386: 32
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
