---
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
nfpms:
  - maintainer: staticdev <staticdev-support@protonmail.com>
    license: "MIT"
    description: |
      Installer package for Clean Contacts.
      Clean Contacts is an utility to cleanup VCard contacts to prevent apps for
      having access to all details of your contacts.
      It strips e-mail, notes, dates and everything from the contacts,
      leaving just the name and phone numbers.
    formats:
      - deb
      - rpm
    contents:
      - src: .lintian-overrides
        dst: ./usr/share/lintian/overrides/cleancontacts
        packager: deb
        file_info:
          mode: 0644

    section: misc
archives:
  - format: zip
    replacements:
      darwin: Mac
      linux: Linux
      windows: Windows
      386: 32
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
