---
name: Tests

"on":
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: '1.17'

      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
