---
name: Tests

"on":
  pull_request:
  push:
    branches: [main]

env:
  GOLANGCI_LINT_VERSION: v2.1

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1

  lint:
    permissions:
      contents: read
      pull-requests: read
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Check out the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  tests:
    name: tests ${{ matrix.go }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {go: "1.23", os: "ubuntu-latest"}
          - {go: "1.23", os: "macos-latest"}
          - {go: "1.23", os: "windows-latest"}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test -v ./...

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run coverage
        run: go test ./... -failfast -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
