---
name: Tests

"on":
  - push
  - pull_request

jobs:
  tests:
    name: tests ${{ matrix.go }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { go: "1.17", os: "ubuntu-latest" }
          - { go: "1.17", os: "macos-latest" }

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test -v ./...

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: '1.17'

      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
